### ISSUE TITLE
can't omit license dialog

### ISSUE THREAD

**Issue by forestmojo** [wschreyer/hepak-tools#1]
hi, wschreyer:

Great thanks for your work, I am using your code. as mentioned in document:
Run python example.py to execute the example script. You may have to acknowledge the dialog showing HEPAK License information (Starting Excel with the Add-In already installed beforehand will suppress this dialog). Then the script will print a few calculated He4 and He3 properties and list some information about the data available in HEPAK.
If I open an excell, then run python example.py, it shows error as following:
C:\Users\Geyang\Desktop\hepak-tools-master>python example.py
Loading HEPAK Excel Add-In. You may have to acknowledge a popup dialog. Launch Excel with HEPAK Add-In already installed to suppress dialog.
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    print('He4 Standard density:', hepak.HeCalc('D', 0, 'P', 101300, 'T', 273.15, 1))
  File "C:\Users\Geyang\Desktop\hepak-tools-master\hepak.py", line 76, in HeCalc
    return xl.Application.Run('HeCalc', property, phase, input1, value1, input2, value2, units)
  File "E:\Temp\cache\gen_py\3.7\00020813-0000-0000-C000-000000000046x0x1x8\_Application.py", line 376, in Run
    , Arg26, Arg27, Arg28, Arg29, Arg30
  File "C:\python3.7\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2146788248), None)

Thanks a lot in advance.

**Comment by wschreyer** [comment]
Hi,
this seems to be some generic error in the win32 COM API. I'm afraid I'm not an expert in that area. Does the hepak Add-In work for you in Excel? You could try some of the simpler functions from the Python module, like HeUnit, HeConst, or HeProperty.
